use_frameworks!

target 'Mylib_Example' do
  pod 'Mylib', :path => '../'

  target 'Mylib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
